### PR TITLE
Fix build with Qt6

### PR DESCRIPTION
**Pull request by jmlich**
I need to check what parts needs conditional compiling for older qt.

### CODE REVIEW

**Review by Thaodan — CHANGES_REQUESTED** [review]
Please read:
Similar to https://github.com/sailfishos/qt-mobility-haptics-ffmemless/pull/1#pullrequestreview-1598788046

**Review by rainemak — CHANGES_REQUESTED** [review]
Cpp changes are missing Qt version checks. Currently this will not build with Qt5.6. Changes needed for searchmodel.cpp & filtermodel.cpp

**Comment by jmlich** [comment]
I am sorry, I was so happy that it finally with Qt 6 that I forgot to make sure that it works also with previous version. I will fix that soon.

**Review by pvuorela — APPROVED** [review]
Builds with Qt 5.6. Seems all good.

**Pull request merged**
